"""Add professional verification fields

Revision ID: 75e59a04c5ab
Revises: d36887c8bf2b
Create Date: 2025-05-21 20:09:55.098812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75e59a04c5ab'
down_revision = 'd36887c8bf2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_portfolio_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.alter_column('certification_file',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_column('portfolio_images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portfolio_images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('certification_file',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    op.drop_table('professional_portfolio_images')
    # ### end Alembic commands ###
